#!/bin/sh

start() {
    /usr/bin/start-raspivid.sh &
}

stop() {
    killall raspivid
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start|stop|restart)
            "$1";;
        reload)
            restart;;
        *)
            echo "Usage: $0 {start|stop|restart|reload}"
            exit 1
esac
